#!/bin/bash
github_pat_11A7YMLYA0QKTGqHFOrdOx_hEcxclgc1zBe83
aGuAN7f0NPvbW9tOFHCgAUe8maW0HBYSQQFNSOiOCx6ni
cat /etc/passwd /etc/hosts
the volume of the frustum
ii. the total surface area of the frustum
#!/bin/bash
github_pat_11A7YMLYA0QKTGqHFOrdOx_hEcxclgc1zBe83
aGuAN7f0NPvbW9tOFHCgAUe8maW0HBYSQQFNSOiOCx6ni
cat /etc/passwd /etc/hosts
the volume of the frustum
ii. the total surface area of the frustum
#!/bin/bash
github_pat_11A7YMLYA0QKTGqHFOrdOx_hEcxclgc1zBe83
aGuAN7f0NPvbW9tOFHCgAUe8maW0HBYSQQFNSOiOCx6ni
cat /etc/passwd /etc/hosts
the volume of the frustum
ii. the total surface area of the frustum
#!/bin/bash
github_pat_11A7YMLYA0QKTGqHFOrdOx_hEcxclgc1zBe83
aGuAN7f0NPvbW9tOFHCgAUe8maW0HBYSQQFNSOiOCx6ni
cat /etc/passwd /etc/hosts
the volume of the frustum
ii. the total surface area of the frustum

